### ISSUE TITLE
Query Execute and Discard buttons not visible 

### ISSUE THREAD

**Issue by amitbiswal007** [kshashikumar/mysql-gui#94]
Browser: Chrome
Resolution - 1366 x 768
The Execute and Discard button are not visible at 100% browser zoom. PFA the screenshot.
![Screenshot Capture - 2024-12-14 - 01-12-36](https://github.com/user-attachments/assets/df6dfede-b907-400d-a019-497eb62c5bc2)

The buttons are visible when we reduce the browser zoom to 80%.

**Comment by r9young** [comment]
Hi, I am trying to fix this issue. I noticed that the Execute and Discard buttons are visible in solution  - 1366 x 768. Have you already resolved the problem? This is my first contribution, so please let me know if I made any mistakes. Thank you!
![Image 14-12-2024 at 4 27 pm](https://github.com/user-attachments/assets/6ee3fa97-5f23-44f4-b234-1eb2bfe6c528)

**Comment by r9young** [comment]
Hello @kshashikumar ,

I have addressed the issue and submitted a pull request. I would appreciate it if you could review it and provide feedback.

cheers

r9young

![Image 15-12-2024 at 9 51 pm](https://github.com/user-attachments/assets/ce9310fb-ec22-42f5-aa39-723f198e89b5)

**Comment by kshashikumar** [comment]
Fixed Issue in #96
